layout_spectrum: 0.38605740184702053
typography_spectrum: 0.5078061865965402
color:
  saturation: 0.96355516181853
  brandStrength: 0.20818952271198432
  rhythmicContrast: 0.5639205545038538
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  lightness: 0.7618651174072472
github: true
opengraph:
  image: null
  type: null
  appId: null
analytics:
  twitter: null
  google: UA-634542-82
  facebook: null
author:
  email: ''
  url: ''
  name: ''
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/6a1f760c-24ff-4080-9f8f-cc997d994ea6.png
name: arstler.com
url: 'http://arstler.com'
cta:
  bucket: null
  version: null
  domain: null
navigation:
  - name: 'arstler™ - in fact, I''d like to steal this painting™'
    id: 8e1e6782-92ec-4bae-b65d-3191a4443bf3
    type: content
  - name: personae
    id: 06f56036-4325-461f-a836-fbb33b1928bc
    type: content
  - name: nothing
    url: 'https://#'
    type: external
  - name: ♥in
    url: 'https://app.thegrid.io/'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/0552a8d3-aeb8-433c-9c16-ed807a5c2ff9.png
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: ''
content: []
description: ''
purpose: []
